import { experimental_useSidebarThreadActions, experimental_useSidebarThreadSplit } from "@get-bb/plugin-sdk/app";
import { ContextMenu, ContextMenuContent, ContextMenuItem, ContextMenuLabel, ContextMenuSeparator, ContextMenuTrigger } from "../ui/context-menu";
import { Icon } from "../ui/icon";

export type ArchivedThread = {
  id: string; projectId: string; title: string | null; titleFallback: string | null; parentThreadId: string | null;
  environmentBranchName: string | null; isPinned: boolean; isUnread: boolean; createdAt: number; updatedAt: number; archivedAt: number;
};

export function ArchivedThreadRow({ thread, project, groups, onUnarchive, onNavigate, onDragThreadChange, onDropTargetChange }: { thread: ArchivedThread; project?: { name: string; isPersonal: boolean }; groups: readonly { id: string; name: string }[]; onUnarchive(threadId: string, destination: string | null): void; onNavigate(): void; onDragThreadChange(threadId: string | null): void; onDropTargetChange(): void }) {
  const actions = experimental_useSidebarThreadActions();
  const { splitProps, isAvailable } = experimental_useSidebarThreadSplit(thread.id);
  const title = thread.title || thread.titleFallback || "Untitled thread";
  const projectLabel = project?.isPersonal ? "Personal" : project?.name ?? "Project";
  return <article className="ws-thread ws-archived-thread"><ContextMenu><ContextMenuTrigger asChild><a href="#" {...splitProps} className="ws-thread-anchor" onClick={(event) => { event.preventDefault(); actions.open(thread.id); onNavigate(); }}><Icon name={project?.isPersonal ? "Laptop" : "FolderGit"} className="ws-project-icon" aria-label={projectLabel} /><span className="ws-thread-main"><span className="ws-thread-title">{title}</span><span className="ws-thread-meta"><span>{thread.environmentBranchName || projectLabel}</span><span>Archive</span></span></span><span className="ws-thread-trailing"><span className="ws-thread-drag-handle" role="button" tabIndex={0} draggable aria-label={`Restore ${title}`} title="Drag to Active or a custom group" onDragStart={(event) => { event.stopPropagation(); event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/plain", thread.id); onDragThreadChange(thread.id); }} onDragEnd={(event) => { event.stopPropagation(); onDragThreadChange(null); onDropTargetChange(); }} onClick={(event) => { event.preventDefault(); event.stopPropagation(); }}><Icon name="GripVertical" aria-hidden /></span></span></a></ContextMenuTrigger><ContextMenuContent aria-label={`Actions for ${title}`}><ContextMenuLabel>{title}</ContextMenuLabel><ContextMenuItem onSelect={() => { actions.open(thread.id); onNavigate(); }}>Open</ContextMenuItem>{isAvailable && <ContextMenuItem onSelect={() => { actions.open(thread.id, { split: true }); onNavigate(); }}>Open in split</ContextMenuItem>}<ContextMenuSeparator /><ContextMenuItem onSelect={() => onUnarchive(thread.id, null)}>Active</ContextMenuItem>{groups.map((group) => <ContextMenuItem key={group.id} onSelect={() => onUnarchive(thread.id, group.id)}>{group.name}</ContextMenuItem>)}<ContextMenuSeparator /><ContextMenuItem className="text-destructive focus:text-destructive" onSelect={() => actions.requestDelete(thread.id)}>Delete</ContextMenuItem></ContextMenuContent></ContextMenu></article>;
}
